spring.application.name=carburant-station-service

spring.ai.mcp.server.name=carburant-station-service-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.protocol=STREAMABLE

# MongoDB Configuration
spring.mongodb.uri=mongodb://${MONGO_USER:mcp_user}:${MONGO_PASSWORD:mcp_secure_password}@localhost:${MONGO_PORT:27017}/${MONGO_DB:mcp_db}?authSource=admin
spring.data.mongodb.auto-index-creation=true

server.port=${SERVER_PORT:8080}