spring.application.name=carburant-station-service

spring.ai.mcp.server.name=carburant-station-service-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.protocol=STREAMABLE

server.port=${SERVER_PORT:8080}